name: turf_cross_platform
description: "Cross-platform migration of the TURF App (Android & iOS)"
publish_to: 'none'

version: 1.6.0+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation & State management
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.2.1

  # Maps & Core Location APIs
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0

  # Hardware Sensors
  pedometer: ^4.0.2
  flutter_compass: ^0.8.1

  # Storage Persistence
  path_provider: ^2.1.2
  uuid: ^4.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Background Tracking & Notifications
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.1

  # Cloud Sync & Database
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.json
    - assets/google_logo.png
    - assets/turf_logo.svg
    - assets/sfx_button_click.wav
    - assets/sfx_start_walk.wav
    - assets/sfx_end_walk.wav
    - assets/sfx_login.wav
    - assets/sfx_logout.wav
    - assets/sfx_recenter.wav
    - assets/sfx_delete_history.wav
    - assets/turf_app_logo.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/turf_app_logo.png"
  remove_alpha_ios: true
  background_color_ios: "#000000"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/turf_app_logo.png"
